### ISSUE TITLE
Area chart with many points blank

### ISSUE THREAD

**Issue by dgorissen** [drarmstr/c3#20]
I notice that when I go beyond ~25000 points in the area plot no longer draws. I still get axes, other layers, I can zoom, etc.  There are no errors and otherwise things seem fine.  Its just that the area layer no longer shows. The elements / path are there in the DOM though.

Perhaps this is too much to handle and I should sub-sample but thought I would report.

**Comment by drarmstr** [comment]
Yes, the intention with C3 is that data should be decimated so that the scale of data points rendered is on the order of what humans can comprehend, and thus in line with what is performant and possible for browsers to render.  Some visualizations have decimation functionality built-in, but the area plot does not.  I generally do decimation at a higher level for area/line charts.  I often used [Crossfilter](https://github.com/crossfilter/crossfilter) for this because I could get decimation relatively cheaply while using it for other functionality as well.  I didn't want to pull that in directly to keep the dependencies/interface clean.
